### ISSUE TITLE
落地页优化建议

### ISSUE THREAD

**Issue by aispin** [JChehe/XCel#1]
### 字体优化

字体改一下，在样式靠前的地方加以下样式：

```
body, button, input, select, textarea {
    font: 300 1em/1.8 "PingFang SC","Lantinghei SC","Microsoft Yahei","Hiragino Sans GB","Microsoft Sans Serif","WenQuanYi Micro Hei",sans
}

h1, h2, h3, h4, h5 {
    font-weight: 100;
}
```

然后样式里面去掉所有的`font-family: 'Montserrat';`

### logo优化

logo直接用样式就行：

```
<div class="logo">筛</div>
```

样式是：

```
width: 50px;
    height: 50px;
    line-height: 50px;
    text-align: center;
    font-size: 1.6em;
    border: 1px solid #666;
    border-radius: 50%;
    margin-top: 14px;
    float: left;
```

注意页面滚动下来，当导航背景色变成黑色时，logo变成白色：

```
border-color:#fff;
color: #fff;
```

### 文案优化

1、关于XCEL

在现在文案的基础上增加以下内容：

> 整个数据筛选处理过程利用NodeJS强大的异步处理功能，让你彻底告别在Excel里面自己写宏函数的卡顿、没响应的原始方式！

2、核心特性

2.1 原生应用

> 基于 Electron 研发并打包成为原生应用，用户体验良好。

2.2 可视化

> 可视化操作你的Excel数据，支持文件的导入导出。

2.3 强大的筛选逻辑

> 提供了单列运算逻辑、多列运算逻辑和双列范围逻辑三种筛选方式，并且可通过“且”、“或”和“编组”的方式任意组合筛选逻辑！

3、 更多特性

3.1 自动更新

> 提供应用的自动更新功能。「正在开发中..」

3.2 免费开源

> 免费开源，欢迎提供 [问题反馈](https://github.com/JChehe/XCel/issues/new) 和 [代码贡献](https://github.com/JChehe/XCel/pulls)

### 增加「下载试用」的段落

在「关于XCEL」段落后面增加「下载试用」的段落，将windows，mac，和linux三种下载方式列出来

样式参考：

![image](https://cloud.githubusercontent.com/assets/85879/20300761/8b6ba2c2-ab5b-11e6-807f-0a2db0199184.png)

按钮的样式为：

```
.btn {
    display: inline-block;
    padding: 5px 15px;
    border: 1px solid #666;
    font-size: 14px;
    border-radius: 5px;
}
```

按钮hover的颜色参考上面icon的样式

### Slogan更新

将`凹凸实验室出品 - Excel 筛选工具` 更改成为

> Excel数据工作者的福音 - 终极数据筛选器

**Comment by JChehe** [comment]
谢谢LV大大的建议~已经修改好了 http://jdc.jd.com/lab/xcel/
