### ISSUE TITLE
客户端下载完无法使用

### ISSUE THREAD

**Issue by otaku1951** [JChehe/XCel#2]
客户端下载后点击XCel.exe，出现一个无界面的东东，貌似没办法用，求解。

**Comment by JChehe** [comment]
@otaku1951 你的系统是什么？下载的程序时多少位的？能否提供一个应用的截图。 谢谢

**Comment by otaku1951** [comment]
@JChehe 
系统是windows 64位的，然后下载的程序名称是XCel-win32-x64
![1](https://cloud.githubusercontent.com/assets/3422957/20336403/bed95fba-ac04-11e6-9731-ccceb2df90a8.png)

**Comment by JChehe** [comment]
@otaku1951 我在公司电脑的windows 7 企业版是可以正常使用的。
你可以在XCEL的窗口激活时，按快捷键 Ctrl + Shift + i 打开开发者工具看看报什么错误。如果没报错的话，再次下载看看行不行。

**Comment by otaku1951** [comment]
@JChehe   报错信息是：
主页面pid： 5376
index.html:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0

**Comment by JChehe** [comment]
@otaku1951 你好，现在修复好了，由于还没实现自动更新，需要重新下载。
下载链接：https://jdc.jd.com/lab/xcel/xcel/XCel-win32-x64.zip
产生BUG的原因是：localStorage 和 JSON.parse 处理不当导致
谢谢你的反馈~🌹

**Comment by otaku1951** [comment]
@JChehe 重新下了，可以用啦 哈哈 赞
